# These are supported funding model platforms

github: [wahyu9kdl]
patreon: wahyu9kdl
paypalme: wahyudi9kdl
open_collective: wahyu9kdl
saweria.co: AwGroupChannel
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["https://www.paypal.com/paypalme/wahyudi9kdl","https://trakteer.id/awfanspage/tip","https://saweria.co/AwGroupChannel"]
